services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]

  # worker:
  #   build:
  #     context: .
  #     dockerfile: worker/Dockerfile
  #   working_dir: /app/worker
  #   container_name: go-worker
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_ADDR=redis:6379
  #   volumes:
  #     - .:/app

  api:
    build:
      context: ./api
      # dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    command: ["sh", "-c", "ls -la /app/api && ./api"]

